### PR TITLE
New pull request pour un partage de code

### PR DESCRIPTION
**Pull request by florianed**

### CODE REVIEW

**Comment by massimotisi** [comment]
Exceptions aprés quelques click sur Next

**Comment by florianed** [comment]
C'est bizarre parce que nous n'en avons pas

**Comment by massimotisi** [comment]
De ma coté l'exception n'est lancée pas toutes le fois (je dirai une fois sur trois).

**Comment by romualdDebruyne** [comment]
Yo Massimo,

J'ai pu constater que de leur coté il n'y a pas d'exceptions qui se 
lèvent... Tu pourrais-être plus précis sur le type d'exception qui se 
lève ????

Romu

Le 24/06/2016 à 16:51, Massimo Tisi a écrit :

> De ma coté l'exception n'est lancée pas toutes le fois (je dirai une 
> fois sur trois).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/CACAO2016/CACAO2016/pull/48#issuecomment-228367281, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AQze7bCCtSYrdUOdy8YS5lh1dHUQQorIks5qO-79gaJpZM4I9xBL.

## 

Mines Nantes http://www.mines-nantes.fr   _Romuald DEBRUYNE_
Maître Assistant, Département DAPI
Tél. : 02 51 85 82 11  La Chantrerie
4 rue Alfred Kastler
BP 20722
44307 Nantes Cedex 3
Site web http://www.mines-nantes.fr Twitter 
https://twitter.com/minesnantes Facebook 
https://fr-fr.facebook.com/pages/%C3%89cole-des-Mines-de-Nantes/117581958064

**Comment by massimotisi** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at javax.swing.text.GlyphView.getBreakSpot(GlyphView.java:799)
    at javax.swing.text.GlyphView.getBreakWeight(GlyphView.java:724)
    at javax.swing.text.html.InlineView.getBreakWeight(InlineView.java:150)
    at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:733)
    at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
    at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
    at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:157)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.ParagraphView.getMinimumSpan(ParagraphView.java:270)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getPreferredSpan(BoxView.java:545)
    at javax.swing.text.html.BlockView.getPreferredSpan(BlockView.java:362)
    at javax.swing.plaf.basic.BasicHTML$Renderer.<init>(BasicHTML.java:383)
    at javax.swing.plaf.basic.BasicHTML.createHTMLView(BasicHTML.java:67)
    at javax.swing.plaf.basic.BasicHTML.updateRenderer(BasicHTML.java:207)
    at javax.swing.plaf.basic.BasicLabelUI.propertyChange(BasicLabelUI.java:417)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8422)
    at javax.swing.JLabel.setText(JLabel.java:330)
    at presentation.FenetreJournal.setLabel(FenetreJournal.java:53)
    at control.CtrlCheckBoxJournal.update(CtrlCheckBoxJournal.java:29)
    at java.util.Observable.notifyObservers(Observable.java:159)
    at abstraction.fourni.Journal.ajouter(Journal.java:49)
    at abstraction.equipe1.IntelligenceEconomique.calculerOffreTotale(IntelligenceEconomique.java:48)
    at abstraction.equipe1.Producteur.actualiserQuantiteProposee(Producteur.java:144)
    at abstraction.equipe1.Producteur.next(Producteur.java:71)
    at abstraction.fourni.Monde.next(Monde.java:153)
    at control.CtrlBtnNext.actionPerformed(CtrlBtnNext.java:16)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by massimotisi** [comment]
et aussi:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at javax.swing.text.GlyphView.getBreakSpot(GlyphView.java:799)
    at javax.swing.text.GlyphView.getBreakWeight(GlyphView.java:724)
    at javax.swing.text.html.InlineView.getBreakWeight(InlineView.java:150)
    at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:733)
    at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
    at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
    at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:157)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.ParagraphView.getMinimumSpan(ParagraphView.java:270)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getPreferredSpan(BoxView.java:545)
    at javax.swing.text.html.BlockView.getPreferredSpan(BlockView.java:362)
    at javax.swing.plaf.basic.BasicHTML$Renderer.<init>(BasicHTML.java:383)
    at javax.swing.plaf.basic.BasicHTML.createHTMLView(BasicHTML.java:67)
    at javax.swing.plaf.basic.BasicHTML.updateRenderer(BasicHTML.java:207)
    at javax.swing.plaf.basic.BasicLabelUI.propertyChange(BasicLabelUI.java:417)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8422)
    at javax.swing.JLabel.setText(JLabel.java:330)
    at presentation.FenetreHistorique.setLabel(FenetreHistorique.java:40)
    at control.CtrlCheckBoxHistorique.update(CtrlCheckBoxHistorique.java:31)
    at java.util.Observable.notifyObservers(Observable.java:159)
    at abstraction.fourni.Historique.ajouter(Historique.java:27)
    at abstraction.fourni.Indicateur.setValeur(Indicateur.java:81)
    at abstraction.equipe2.Nestle.next(Nestle.java:413)
    at abstraction.fourni.Monde.next(Monde.java:153)
    at control.CtrlBtnNext.actionPerformed(CtrlBtnNext.java:16)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by massimotisi** [comment]
@romualdDebruyne: tu peux essayer sur ton ordi si tu veux en telechargeant le zip https://github.com/florianed/CACAO2016/archive/master.zip

**Comment by romualdDebruyne** [comment]
Ni elle ni moi n'avons su le faire planter... On a importer ton archive 
mais il n'y a jamais de levée d'exception....

Romu

Le 24/06/2016 à 17:08, Massimo Tisi a écrit :

> @romualdDebruyne https://github.com/romualdDebruyne: tu peux essayer 
> sur ton ordi si tu veux en telechargeant le zip 
> https://github.com/florianed/CACAO2016/archive/master.zip
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> https://github.com/CACAO2016/CACAO2016/pull/48#issuecomment-228371697, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AQze7UJrVMh72NqnkSYshPiSyMXI-VmIks5qO_LUgaJpZM4I9xBL.

## 

Mines Nantes http://www.mines-nantes.fr   _Romuald DEBRUYNE_
Maître Assistant, Département DAPI
Tél. : 02 51 85 82 11  La Chantrerie
4 rue Alfred Kastler
BP 20722
44307 Nantes Cedex 3
Site web http://www.mines-nantes.fr Twitter 
https://twitter.com/minesnantes Facebook 
https://fr-fr.facebook.com/pages/%C3%89cole-des-Mines-de-Nantes/117581958064

**Comment by florianed** [comment]
Non.. J'ai beau essayer, je suis vraiment désolée mais je n'ai pas d'exceptions.

**Comment by massimotisi** [comment]
En regardant le stacktrace il semble un probleme de rendering html dans le Journal. 
@jhtr: votre journal utilise un html assez complexe et c'est possible que le rendering html ne marche pas dans la meme faiçon dans toutes les plateformes (je suis sur macOs et java8). 
@florianed: pour l'instant je vous permit de commenter les lignes 48-55 de equipe1/IntelligenceEconomique.java

**Comment by massimotisi** [comment]
@florianed: avec votre dernier commit chaque click sur next est devenu _beaucoup_ plus long. 
@romualdDebruyne: Mon impression est que il faut utiliser le journal seulement pour des messages d'une seule ligne par click sur next

**Comment by florianed** [comment]
Devons nous changer ca?

**Comment by massimotisi** [comment]
Aprés le dernier commit les performance sont retournées acceptables, merci.
Si vous commentez les lignes 48-55 de equipe1/IntelligenceEconomique.java je vais accepter la pull request.
Aprés ce sera à @jhtr de simplifier l'affichage du journal de l'equipe1 dans la prochaine pull request

**Comment by florianed** [comment]
C'est fait, pour notre part.

**Comment by massimotisi** [comment]
Pour info. La cause de l'exception est un bug dans Java8: https://bugs.openjdk.java.net/browse/JDK-8060036 
Le bug a ete resolu dans le JDK 8u60: http://www.oracle.com/technetwork/java/javase/2col/8u60-bugfixes-2620228.html

@jhtr: vous pouvez re-ajouter votre affichage html, si vous voulez
@florianed, @jhtr, @AlexandreMarty, @MarcSuteau, @SofianeSalort, @lakac: pour garder des performances acceptables, limités vous à une seule appelle à la methode Journal.ajouter() à chaque next()

**Pull request merged**
